{"uuid": "a9aa684e-75c9-4e8c-bf76-174354430bb1", "children": ["2abb38a3-fb8e-4875-8afe-2c2d6fe34706"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/user/PycharmProjects/home_work_6_12/conftest.py\", line 51, in setup_browser\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/user/PycharmProjects/home_work_6_12/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 209, in check_response\n    raise exception_class(value)\n"}, "start": 1689529659872, "stop": 1689529660430}], "start": 1689529659872, "stop": 1689529660542}